### ISSUE TITLE
cannot import name metrics

### ISSUE THREAD

**Issue by shaunak-badani** [rmcgibbo/mullermsm#4]
Hi, 
     I tried installing using the clone method, then running the setup script in a conda environment. I installed theano as well. After running the `mullermsm_propagate.py` command, I get the error : 

`cannot import name metrics`.

I have attached a screenshot. Any help would be much appreciated.
![Screenshot from 2022-01-07 16-19-26](https://user-images.githubusercontent.com/32260623/148533266-1b53321f-4335-4ac7-9754-b8f2c6fd0ba9.png)

**Comment by rmcgibbo** [comment]
Hi. I'm sorry, as you can see from the github main page this repository was last touched ~10 years ago. Obviously all of the dependencies (python, python packaging, numpy, etc) have changed a lot in that time, and I'm not able to offer support now. Good luck.
